=== RogerGuevara555/FP/Lenguajes de marcas/UT2/Act 2.10 (Tarea)/dtd_Roger_Guevara_Troche/roger_guevara_troche.dtd
<!ELEMENT curriculums (cvEuropass)*>

<!ELEMENT cvEuropass (datos_personales, descripcion, experiencia_laboral, tecnologias, formacion, idiomas)>
<!ATTLIST cvEuropass id ID #REQUIRED>

	<!ELEMENT datos_personales (nombre, apellidos, sexo, nacionalidad, codigoPais, domicilio, contacto)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT sexo (#PCDATA)>
		<!ELEMENT nacionalidad (#PCDATA)>
		<!ELEMENT codigoPais (#PCDATA)>

		<!ELEMENT domicilio (numero?, calle?, codigoPostal?, ciudad)>
			<!ELEMENT numero (#PCDATA)>
			<!ELEMENT calle (#PCDATA)>
			<!ELEMENT codigoPostal (#PCDATA)>
			<!ELEMENT ciudad (#PCDATA)>

		<!ELEMENT contacto (correo, telefono)>
			<!ELEMENT correo (#PCDATA)>
			<!ELEMENT telefono (#PCDATA)>

	<!ELEMENT descripcion (#PCDATA)>
         
	<!ELEMENT experiencia_laboral (experiencia)*>
		<!ELEMENT experiencia (puesto, empresa)>
		<!ATTLIST experiencia inicio CDATA #REQUIRED>
		<!ATTLIST experiencia fin CDATA #IMPLIED>
		<!ATTLIST experiencia actual (true | false) #IMPLIED>
			<!ELEMENT puesto (#PCDATA)>
			<!ELEMENT empresa (#PCDATA)>

         
	<!ELEMENT tecnologias (tecnologia)*>
		<!ELEMENT tecnologia (#PCDATA)>
		<!ATTLIST tecnologia nivel (basico | intermedio | avanzado) #REQUIRED>
		 
	<!ELEMENT formacion (curso)*>
		<!ELEMENT curso (titulacion, centro, (modalidad | tipoCentro)?)>
		<!ATTLIST curso inicio CDATA #REQUIRED>
		<!ATTLIST curso fin CDATA #IMPLIED>
		<!ATTLIST curso actual (true | false) #IMPLIED>
			<!ELEMENT titulacion (#PCDATA)>
			<!ELEMENT centro (#PCDATA)>
			<!ELEMENT modalidad (#PCDATA)>
			<!ELEMENT tipoCentro (#PCDATA)>
			
	<!ELEMENT idiomas (codigoIdioma+)>
		<!ELEMENT codigoIdioma (#PCDATA)>
		<!ATTLIST codigoIdioma nivel CDATA #REQUIRED>



<!ENTITY centro_ies "IES Virgen de la Paz">

=== RogerGuevara555/FP/Lenguajes de marcas/UT2/Act 2.10 (Tarea)/dtd_Roger_Guevara_Troche/roger_guevara_troche.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE curriculums SYSTEM "roger_guevara_troche.dtd">

<curriculums>


  <cvEuropass id="cv-1">

    <datos_personales>
      <nombre>Roger</nombre>
      <apellidos>Guevara Troche</apellidos>
      <sexo>Masculino</sexo>
      <nacionalidad>Cubana</nacionalidad>
      <!-- Estándar ISO 3166-1 alfa-2 -->
      <codigoPais>ES</codigoPais>
      <domicilio>
        <numero>6</numero>
        <calle>Jarama</calle>
        <codigoPostal>28100</codigoPostal>
        <ciudad>Alcobendas</ciudad>
      </domicilio>
      <contacto>
        <correo>rogerandres555@gmail.com</correo>
        <telefono>(+34) 614-659-509</telefono>
      </contacto>
    </datos_personales>

    <descripcion>
      Estudiante de informática con gran pasión por la programación y dispuesto a entrar un sector en constante cambio.
    </descripcion>

    <experiencia_laboral>
      <!-- Añadir cuando tenga experiencia. -->
    </experiencia_laboral>

    <tecnologias>
      <tecnologia nivel="avanzado">Java</tecnologia>
      <tecnologia nivel="avanzado">Python</tecnologia>
      <tecnologia nivel="intermedio">Git</tecnologia>
      <tecnologia nivel="basico">SQLite</tecnologia>
    </tecnologias>

    <formacion>
      <curso inicio="2023-09" fin="2025-06">
        <titulacion>Bachillerato</titulacion>
        <centro>IPVCE Vladimir Ilich Lenin</centro>
        <tipoCentro>Becado</tipoCentro>
      </curso>
      <curso inicio="2026-09" actual="true">
        <titulacion>Grado Superior en DAM</titulacion>
        <centro>&centro_ies;</centro>
        <modalidad>Dual</modalidad>
      </curso>
    </formacion>

    <idiomas>
      <codigoIdioma nivel="C2">es</codigoIdioma>
      <codigoIdioma nivel="B1">en</codigoIdioma>
      <!-- Código ISO 639-1 -->
    </idiomas>

  </cvEuropass>
	

</curriculums>
